### ISSUE TITLE
Chrome videos do not load in FP7.

### ISSUE THREAD

**Issue by eschie** [flowplayer/flowplayer#1158] opened 2017-02-28 23:27 UTC
I believe this is related to #1135 .

For Chrome 56 iOS 10.0.2, 9.3.3, iPhone 6, FP7:
Video loads, audio plays, subtitles update at the appropriate times, but **the video does not progress**. Only a static image is served and occasionally/intermittently updates to a later point in the video after some interaction. 

![cr56ios9](https://cloud.githubusercontent.com/assets/1564750/23439854/9519bbf0-fdcd-11e6-8d7f-ad0148243ca2.gif)

The video **DOES** play on Chrome 56 iOS 10.2.1 iPhone 5.

**Comment by nnarhinen** [comment] 2017-03-02 23:23
How about plain video tag - http://demos.flowplayer.org/videotest/minimal.html
Or plain video tag with playsinline attribute - http://demos.flowplayer.org/videotest/playsinline.html

**Comment by nnarhinen** [comment] 2017-03-06 10:56
Closing until more information. Feel free to re-open with the needed information.

**Comment by waraulin** [comment] 2017-03-06 22:55
@nnarhinen - I'm on @eschie's team. I've tested both of the above links on Chrome 56 iOS 10.0.2 iPhone 6 and both seemed to play normally, although no subtitles displayed nor did I have an option to turn on subtitles anywhere.

**Comment by nnarhinen** [comment] 2017-03-07 10:21
Ok, so to clarify:

On iPhone with iOS 10.x, using Chrome browser, all these three links opened with the same device and browser:

 * http://demos.flowplayer.org/videotest/minimal.html - video plays in the fullscreen quicktime video component?
 * http://demos.flowplayer.org/videotest/playsinline.html - video plays inline the page in the standard HTML5 video tag?
 * http://demos.flowplayer.org/basics/minimal.html - video does not play? Flowplayer UI is shown, audio is heard but video is frozen?

**Comment by waraulin** [comment] 2017-03-08 02:22
@nnarhinen - sorry for the delay. After more testing I've found that videos on all three links function as intended on iPhone with iOS 10 on Chrome. It seems that the issue pertains only to iOS 9. On iOS 9, the video on the first link plays normally, video on the second link doesn't play inline (because html5 inline video isn't supported in iOS 9, correct?), and the video on the third link exhibits the issue behavior outlined above by @eschie.

To clarify - the noted issue is present for iOS 9 on Chrome 56 **and not** on iOS 10 on Chrome 56

**Comment by nnarhinen** [comment] 2017-03-08 10:23
Ok, on browserstack the 9.x device does not play video in plain video tag either on chrome. Makes testing hard as I don't have an 9.x device around to see this behaviour on an actual device.

**Comment by nnarhinen** [comment] 2017-03-08 10:24
Could you please test with your actual device a demo with Flowplayer 6.0.5 (http://demos.flowplayer.org/v6/basics/minimal.html)

Does the behaviour differ between FP7 and FP6?

**Comment by waraulin** [comment] 2017-03-11 01:08
Sorry for the delay yet again! FP6 is functioning normally and only FP7 is malfunctioning. Thanks!

**Comment by Teranode** [comment] 2017-03-29 11:57
This is also varying on different videos, sometimes it works other times it doesnt. There's also a case where this happens if you have the vast plugin enabled. (with the same varying results)

**Comment by nnarhinen** [comment] 2017-09-23 20:59
Old issue. Please re-open if this still is an issue.

**Closed by nnarhinen** 2017-09-23 20:59 UTC
