### ISSUE TITLE
On full screen mode in safari 11 cannot close full screen

### ISSUE THREAD

**Issue by NuttaponTamburanavit** [flowplayer/flowplayer#1269] opened 2017-09-29 06:48 UTC
We are encountering with the fullscreen on Safari 11. Whenever the video is in fullscreen mode, we can not get it back to the normal mode as the fullscreen expansion mode remains on the top right corner of the video.

The only way that we can make it collapse to normal screen is to use the ESC button. However, with this approach. The icon is changed to collapse icon which causes unexpected behavior as we can no longer expand the video.

Is there anyway to resolve the following issue? We have been spending so long figuring out how to solve it.

**Comment by nnarhinen** [comment] 2017-09-29 07:04
Duplicate of #1203

**Closed by nnarhinen** 2017-09-29 07:04 UTC

**Comment by NuttaponTamburanavit** [comment] 2017-10-02 06:25
Yeah, I found but I met new problem on safari version 11 when I update os to high sierra.
