### ISSUE TITLE
Subtitles sometimes doesn't hide when it reaches subtitleEnd

### ISSUE THREAD

**Issue by sibidharan** [flowplayer/flowplayer#1401] opened 2018-07-23 12:41 UTC
Sometimes, the subtitles stays on screen and doesn't disappear when it reaches it's end. 

The problem is caused by the line 2930 to 2938 -

```
  p.bind("cuepoint", function(e, api, cue) {
    if (cue.subtitle) {
       currentPoint = cue.index;
       p.showSubtitle(cue.subtitle.text);
    } else if (cue.subtitleEnd) {
       p.hideSubtitle();
       currentPoint = cue.index;
    }
  });
```

which I modified as following 

```
  p.bind("cuepoint", function(e, api, cue) {
    if (typeof cue.subtitle !== "undefined") {
       currentPoint = cue.index;
       p.showSubtitle(cue.subtitle.text);
    } else if (typeof cue.subtitleEnd !== "undefined") {
       p.hideSubtitle();
       currentPoint = cue.index;
    }
  });
```

This fixed the issue of subtitles staying on screen even when the subtitle has been ended.

Please apply the fix to the final version and commercial version too.

**Comment by nnarhinen** [comment] 2018-08-07 07:24
Duplicate of #1363

**Closed by nnarhinen** 2018-08-07 07:24 UTC
