### ISSUE TITLE
FP7 does not work in IE9

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#1170] opened 2017-03-29 09:44 UTC
http://demos.flowplayer.org/basics/minimal.html
fails with an "SCRIPT5007: Unable to get value of the property ‘length’: object is null or undefined" error.

**Comment by blacktrash** [comment] 2017-03-29 14:59
Is this a duplicate of https://github.com/flowplayer/flowplayer/issues/1157 ?

**Comment by bbbo** [comment] 2017-03-29 15:57
ah, probably.

**Comment by nnarhinen** [comment] 2017-03-30 07:20
If http://demos.dev94.flowplayer.us/basics/minimal.html# works, then this is a duplicate. Please re-open if this is not the case.

**Closed by nnarhinen** 2017-03-30 07:20 UTC

**Comment by bbbo** [comment] 2017-03-30 09:41
works, all good.
