### ISSUE TITLE
embed code not copy

### ISSUE THREAD

**Issue by kabsila** [flowplayer/flowplayer#1216] opened 2017-07-13 14:03 UTC
both html and javascript setup,  if set a title string embed code will not copy when click embed button.

**Comment by blacktrash** [comment] 2017-07-13 14:57
I presume this is a duplicate of #1205 - the title string contains non-ascii characters?
Please confirm. Otherwise please provide a link to a *minimal* sample page demonstrating the problem, please.

**Comment by kabsila** [comment] 2017-07-14 03:23
Yes, it contains non-ascii characters.

**Comment by blacktrash** [comment] 2017-07-14 11:41
@kabsila - thanks.
Closing as it's a duplicate of #1205.

**Closed by blacktrash** 2017-07-14 11:41 UTC
