### ISSUE TITLE
Adobe Flash message following live stream resume

### ISSUE THREAD

**Issue by colmaengus** [flowplayer/flowplayer#1002] opened 2016-03-01 12:43 UTC
If you pause a live rtmpt stream and then resume you get the following message in the corner of the player "Adobe Flash is disabled for this page, click player area to enable"

The message goes way and the video starts playing but it would be nicer if it wasn't there.

I'm using Flowplayer 6.0.5.

**Comment by blacktrash** [comment] 2016-03-01 16:53
There are various scenarios where this sometimes happens. I believe this is caused by the workaround for this issue caused by a, ermh, debatable, Chrome decision: #922 - which opens some timing traps.

**Comment by nnarhinen** [comment] 2016-08-27 00:34
Closing in favor of #1027

**Closed by nnarhinen** 2016-08-27 00:34 UTC
