### ISSUE TITLE
FP7: Problem with the sound during playback RTMP

### ISSUE THREAD

**Issue by thekrzos** [flowplayer/flowplayer#1159] opened 2017-03-04 21:21 UTC
I'm using Chrome 56 and Firefox 51 on Windows 10.
Audio was broken in Flowplayer 7 Flash. I'm playing 1kHz tone.
When playing music can be heard changing tempo during playback.
![22-06-42](https://cloud.githubusercontent.com/assets/6432749/23582347/6efb1794-0128-11e7-99ab-ec50dd921b82.jpg)
![22-05-19](https://cloud.githubusercontent.com/assets/6432749/23582349/73e0d73a-0128-11e7-8198-dd5b46964696.jpg)
![22-09-33](https://cloud.githubusercontent.com/assets/6432749/23582350/75e81746-0128-11e7-9700-895a8d2b3a26.jpg)

**Comment by blacktrash** [comment] 2017-03-06 11:05
We can't see how this is affected by Flowplayer:
- the audio itself is output by Flash, the player only sets up the Flash object
- nothing has changed in the RTMP code itself since version 6
Are you absolutlely sure that your testing environment was exactly the same?
- same browser
- same Flash version?
Does this only happen in this specific Chrome version on the same machine?
Does this always happen, independent of network status?

**Comment by nnarhinen** [comment] 2017-03-06 11:16
If you really think this is an issue with Flowplayer, provide sample urls:
 * One with FP7
 * One with FP6

Exactly the same setups, only flowplayer version should differ.

**Comment by thekrzos** [comment] 2017-03-06 11:18
I'm solved my problem by using SWF from old flowplayer 6.
In config: swf: "/assets/flowplayer-6/flowplayer.swf"

06.03.2017 12:16 PM "Niklas Närhinen" <notifications@github.com> napisał(a):

**Comment by nnarhinen** [comment] 2017-03-06 13:56
In lack of reproduce information I'll close this.

**Closed by nnarhinen** 2017-03-06 13:56 UTC
