### ISSUE TITLE
Flowplayer with fancybox fails in mac.

### ISSUE THREAD

**Issue by jagadeeshv16** [flowplayer/flowplayer#1030] opened 2016-05-30 12:37 UTC
![fancybox-fail](https://cloud.githubusercontent.com/assets/6297068/15649656/c6e529b8-2690-11e6-9748-bdc4fff4199a.png)

This image is when i am trying to run the demo in http://demos.flowplayer.org/scripting/overlay-fancybox.html. on osx 10.11 with safari. When i pause the video 4-5 times. it immediately closes the video and displays the overlay box only.

Any solutions on how to overcome this issue.

**Comment by blacktrash** [comment] 2016-05-30 21:18
I cannot reproduce this so far. Which Safari version is this? Here Mac OS 10.10.5, Safari 9.1.1
Do you have any Safari addons enabled by any chance?

**Comment by jagadeeshv16** [comment] 2016-05-31 05:54
No addons , i am using Safari 9.0.3 and a client reported he is facing the same issue in chrome and safari. he is using 2009 MacBook Pro  running Mavericks.

**Comment by blacktrash** [comment] 2016-05-31 07:52
Hm, I created the demo in 2013, I am on a Mac, and never experienced the issue when testing.
I'll try harder to reproduce, also on other Macs.
Do you get errors in the console when this happens?

**Comment by blacktrash** [comment] 2016-05-31 09:59
No need, I don't doubt that you're experiencing this and presume you wouldn't have gone to the trouble of reporting it otherwise - here's proof that I try really hard to 'break' it, but fail: http://d12zt1n3pd4xhr.cloudfront.net/x/fp-fancybox.mp4 ;-)

Do you experience issues with this demo http://demos.flowplayer.org/scripting/overlay-jquerytools.html as well? - I'm just trying down to narrow down what could be the problem.

**Comment by jagadeeshv16** [comment] 2016-05-31 12:15
You can find the video https://www.dropbox.com/s/gmmbsl08lkow32v/failed-fancybox.mp4 which shows the bug. I am now certain of what the issue is. Here are steps how i was able to replicate the bug.

1. Click on link
2. when video starts playing, pause it
3. Hit space key 5-6 times (we use space to play/pause the video, eventhough, In the flowplayer demo this feature is disabled, hitting space few times raised the bug even in demos section).
4. Play and pause with mouse a few times. 
The empty overlay box should appear

So the bug seems to be hitting **space** key in fancybox overlay.

**Comment by blacktrash** [comment] 2016-05-31 13:55
Thanks. Got it.
One has to disable the space key for fancybox, bound by default to 'play' to toggle slideshow, I gather from a quick search. - http://fancyapps.com/fancybox/#docs
Adding: `keys: {play: null}` to the fancybox config seems to do the trick.

**Comment by blacktrash** [comment] 2016-05-31 14:32
@jagadeeshv16 - should be fixed in our demo once the changes have propagated.

**Closed by blacktrash** 2016-05-31 14:32 UTC
