### ISSUE TITLE
iphone/ipad ios 6.1 problem: player does not run anymore after second time playing

### ISSUE THREAD

**Issue by zwerfkat** [flowplayer/flowplayer#860] opened 2015-06-17 11:59 UTC
Used demo page: http://demos.dev94.flowplayer.us/basics/native_fullscreen.html
Find in: Flowplayer version 6.0.0 and 6.0.1 (older version do work ok)
Client: Safari iphone/ipad ios 6.1 

steps to reproduce:
-open the demo page in Safari (the splash screen isn't showed for one reason or the other)
-click on the play button: it starts buffering for a few seconds and then the native player start to play
-click on Done
-Flowplayer with the normal play button is showed again. So far so good. 
-Press the play button again
-Now the native video player is showed but the video is paused! Luckily the video can be started again by using the native play button.
-click on Done. Now the state of Flowplayer has either changed to buffering (3 dots) or the player has completely died (white screen with a gray play button). If the state is changed to buffering, it does not react anymore at all. So after playing for the second time we have a dead player.

See also the pictures below.

Normal screen but without splash:
![no_splash](https://cloud.githubusercontent.com/assets/40199/8206201/cae59f76-14f7-11e5-9c33-1d2335ef8fcb.jpg)

Done button from native player:
![done](https://cloud.githubusercontent.com/assets/40199/8206269/351939c0-14f8-11e5-85b4-2f9a86ba18b0.jpg)

After playing for the second time, the player seems to be in buffering state but does not react anymore:
![buffering](https://cloud.githubusercontent.com/assets/40199/8206209/de164348-14f7-11e5-8c20-822c709d58d8.jpg)

Or has completely died:
![ios_error](https://cloud.githubusercontent.com/assets/40199/8206210/e2fad194-14f7-11e5-8388-20736367dc41.jpg)

**Comment by zwerfkat** [comment] 2015-06-17 12:32
Seems to be closely related to the fix of issue #530 "Trigger player unload when 'done' pressed on iOS"
Because when I comment out:
//webkitendfullscreen: 'unload'
it is working again!

**Comment by nnarhinen** [comment] 2015-06-17 14:28
Duplicate of #831

**Closed by nnarhinen** 2015-06-17 14:28 UTC
