### ISSUE TITLE
iPhone: subtitle menu not reliably shown

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1051] opened 2016-09-20 16:57 UTC
At least in video tag based installs. At https://flowplayer.org/standalone/basics/subtitles.html the menu sometimes appears, sometimes not:
![iphone-no-cc-menu](https://cloud.githubusercontent.com/assets/168338/18680247/cbedfd2c-7f5a-11e6-83e2-5b52a4dbd727.png)
See also: https://flowplayer.org/forum/#!/setup_configuration:iphone-non-inline-subtitl

With JS installation this seems more reliable: http://flowplayer.blacktrash.org/fp6/subtitles-test.html
However, by default (in spite of specifying a default track), there's a) always an 'Unknonwn CC' menu entry, and b) it defaults to that entry, and no subtitles are shown (by default):
![iphone-unknown-cc](https://cloud.githubusercontent.com/assets/168338/18680451/bbe2114c-7f5b-11e6-9b5c-8594aa73f34a.png)

**Comment by nnarhinen** [comment] 2016-10-27 20:19
Does the "Unknown CC" only appear when playing HLS?

If yes, then this is related and can be resolved with modifications to the HLS manifest: https://developer.apple.com/library/content/qa/qa1801/_index.html

**Comment by nnarhinen** [comment] 2016-10-27 20:22
https://flowplayer.org/standalone/basics/subtitles.html always shows me the subtitles (and menu) in iPhone simulator (9.3 and 10.0 tested)

**Comment by blacktrash** [comment] 2016-10-28 00:53
I didn't make the screenshot up (9.2 iirc) ;-), and https://flowplayer.org/standalone/basics/subtitles.html does not have a HLS source.
These are only observations about VTT _files_, not HLS caption tracks.
The device behavior with CLOSED-CAPTIONS can also be, ermh, surprising, already in video tag. It's a right mess.

**Comment by nnarhinen** [comment] 2016-10-28 05:37
Yeah but https://flowplayer.org/standalone/basics/subtitles.html does not show the "Unknown CC" for me,  http://flowplayer.blacktrash.org/fp6/subtitles-test.html does (has HLS source)

**Comment by blacktrash** [comment] 2016-10-28 08:49
Exactly. I forgot to mention that for Drive I tested with CLOSED-CAPTIONS=NONE to signal that there is no alternate CAPTIONS hls track to the device. With the effect that at least one iPhone then refused to play the movie at all when a VTT track was specified in the video tag.
It's a mess.

**Comment by nnarhinen** [comment] 2016-11-08 00:08
Just saying we can't do anything for the "Unknown CC", it's a Mobile Safari bug.

**Comment by realalexhomer** [comment] 2016-11-08 00:10
It has something to do with video encoding, not flowplayer

**Comment by blacktrash** [comment] 2016-11-08 01:12
@realalexhomer - in what way?
The comparisons here were made with the same media assets for 2 scenarios. The iOS "behavior" varies from version/device to version/device for each of
1. MP4 + VTT file
2. HLS manifest with CLOSED-CAPTIONS=none (i.e. signaling that there is no captions stream)

**Comment by nnarhinen** [comment] 2016-11-08 01:16
But to the original issue..

I can't reproduce any case where the subtitle menu wouldn't be shown. It must be some weird timing issue I can't seem to trigger.

**Comment by nnarhinen** [comment] 2016-11-21 10:11
With the upcoming inline support I deem this issue a weird corner case unless some reliable reproduce steps can be given.

**Closed by nnarhinen** 2016-11-21 10:11 UTC
