### ISSUE TITLE
Firefox: seek broken in video tag

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#937] opened 2015-10-16 19:59 UTC
EDIT: not a Flowplayer problem, but a Firefox bug: Seeking is essentially broken.

Can easily be observed with longer videos in this demo:
http://demos.flowplayer.org/basics/splash.html
1. Firefox
2. empty cache
3. start playback
4. seek way into video
5. switch to a fixed resolution (quality selector uses seek in load callback internally)
6. a) switch takes much longer than in other browsers b) playback stalls or c) buffering animation persists

**Comment by blacktrash** [comment] 2015-10-16 20:05
Case more isolated in this demo: http://demos.flowplayer.org/bug/937.html
Affects only VOD, not HTTP streaming in MediaSource (HLS or MPEG-DASH); MP4 behaves somewhat better, but also not reliable.

imho it's worth investigating how deals with the video tag's progress event, and how often it is triggered.

**Comment by blacktrash** [comment] 2015-10-17 08:58
Unless it's my machine it looks like there's a massive problem with Firefox seeking in plain video tags, independent of Flowplayer. I experience the stalling on seek in a bare video tag:
http://flowplayer.blacktrash.org/test/videotag-webm.html
Firefox 41.0.2 (Mac)

**Comment by blacktrash** [comment] 2015-10-17 11:39
Firefox bug filed here: https://bugzilla.mozilla.org/show_bug.cgi?id=1215802

**Comment by blacktrash** [comment] 2015-10-17 11:42
Leaving open for monitoring Firefox status.

**Comment by bbbo** [comment] 2015-10-17 15:45
seems to be fixed in Firefox 42. Confirmed to be a FF bug.

**Comment by nnarhinen** [comment] 2015-10-20 09:14
If the video tag is broken (and fixed) is there anything we should do? Disabling `seek()` for certain firefox versions feels dirty..

**Comment by bbbo** [comment] 2015-10-20 09:17
I don't think it's worth the trouble, at the speed of FF updates the problem should be gone soon

**Closed** 2015-10-20 13:16 UTC
Labels: critical
