### ISSUE TITLE
FP7 - DVR time 

### ISSUE THREAD

**Issue by popler** [flowplayer/flowplayer#1102] opened 2017-01-15 09:12 UTC
There is a problem with time counter (on the left) during playing live stream with DVR. If time of record is litmited on the server (eg to 1 hour) and user is playing stream longer, he can rewind video before server record. Player is going back to live in this situation, but it is confusing for users. Time on the should be updated or stopped when max DVR record is reached.
It will much easier for users when time to rewind will shown during mouseover event with timeline.

**Comment by blacktrash** [comment] 2017-01-15 12:47
@popler - at least the jump back was a problem with the hlsjs plugin, which I just fixed.
The behaviour is still not entirely like with generic playback, one needs additional seeks when going to cached(?) positions, but it's not consistent with Flash HLS.
However, in generic playback the timer updates usually too, so that part I'm not sure about.

**Comment by blacktrash** [comment] 2017-01-15 12:52
See also: https://flowplayer.org/forum/#!/setup:dvr-timeline

**Comment by popler** [comment] 2017-01-15 13:37
Thank you, I will test new flowplayer-hlsjs. I think that one issue is still to resolve. User still have possibility to jump early than server side record (if it is set to limited time) or chunks in local browser cache.

**Comment by nnarhinen** [comment] 2017-01-16 07:40
Example setup please. This all depends on the DVR streams etc..

**Comment by blacktrash** [comment] 2017-01-16 08:31
http://demos.flowplayer.org/basics/dvr.html - let it play for a while, then seek to 0 by hitting 0 on the keyboard.
Happens with all streams I've seen so far, sometimes you just have to wait longer.

**Comment by blacktrash** [comment] 2017-01-16 08:39
Other stream:
http://flowplayer.blacktrash.org/fp7/dvr.html (with hlsjs)
http://flowplayer.blacktrash.org/fp7/dvr.html?hlsjs=false (with flash hls)
Compare with native playback.

**Comment by blacktrash** [comment] 2017-01-16 15:20
@nnarhinen - with a non incrementing DVR window you would have also a non incrementing time display on the left during playback like here: http://flowplayer.blacktrash.org/fp7/dash-live.html
With and event DVR stream, it would be incremental, somewhat like here: http://demos.flowplayer.org/api/dash.html#dashdvr

**Comment by nnarhinen** [comment] 2017-01-19 11:26
I'm very much confused about this issue. Can you give me simple reproduce steps.. (1. Load page X, 2. Hit something, 3. See what happens/should've happened..)

**Comment by popler** [comment] 2017-01-19 11:41
When you have time limited DVR on server, and playing live time on the should not be bigger than server DVR record time. So if you set DVR limit on server to 10 minutes, stream on server starts more than 10 minutes ago, left time display should pause on 10 minutes during live playing. If it is bigger user can jump with controls before server DVR file.

**Comment by blacktrash** [comment] 2017-01-20 18:20
As far as I can see this is now only a problem with the hlsjs plugin.
One of the problems is that `videoTag.seekable.start(null)` is *always* `0` with hlsjs.
Here's a demo which gives kind of the desired functionality: https://flowplayer.blacktrash.org/fp7/dvr.html - but the time display and scrubber are of course all wonky.

**Comment by blacktrash** [comment] 2017-01-20 20:16
My implementation is more like the one for DASH: http://demos.flowplayer.org/api/dash.html#dashlive
See also: https://github.com/dailymotion/hls.js/issues/65
Current state can be inspected at https://flowplayer.blacktrash.org/fp7/dvr.html

**Comment by blacktrash** [comment] 2017-01-21 11:18
@popler - this should work now with hlsjs, and also in the same way as with native or Flash hls.
Please test by loading `//releases.flowplayer.org/hlsjs/flowplayer.hlsjs.min.js` as recommended.

**Comment by popler** [comment] 2017-01-21 14:56
@blacktrash - I'm not sure it is working as it should. You can check live stream at http://www.popler.tv/embed/player7.php?user=poplerhd. I limitted DVR time on server to 10 minutes. The time on left starts from 10 minutes and going on, so after some time of watching you can rewind more than ten minutes. I can see only one different - when you jump back to live from DVR playing time on the left starts from 10 min again.

**Comment by blacktrash** [comment] 2017-01-21 15:21
Hm, with your example, I can see a problem with _native_ HLS after while, when seeking to the beginning: the progress bar jumps forward to a later position, and large portions are unreachable - @nnarhinen?
@popler, right now I'm fixated on hls.js, and you can verify here that it definitely does not try to go back before the beginning of the dvr window: https://flowplayer.blacktrash.org/fp7/dvr.html (seek to begining after a while).

I have to admit that I find the current time handling confusing, a "fixed" DVR window would be easier to grasp for me personally; but I try to emulate the core behaviour which updates the window somewhat magically.

**Comment by blacktrash** [comment] 2017-01-21 15:49
For comparison, the dash engine via dash.js currently creates a "fixed" DVR window (when it's sliding, not incremental), best seen here: https://flowplayer.blacktrash.org/fp7/dash-live.html - all time display is completely static, unless one seeks.
I don't know what is expected.

**Comment by popler** [comment] 2017-01-21 15:53
@blacktrash I'm expecting the same with HLS as dash.js. Static time display when it is go to max time of DVR window.
I was testing your example, but I had some problem with progress bar. I was watching more than 30 minutes (display on the left), Next I clicked on left end of progress bar, time on the left show someting about 20 min, but progress bar was all white and could not go beck to live.

**Comment by blacktrash** [comment] 2017-01-21 16:06
@popler - that problem should be fixed, you may have to reload (*if* you're talking about the hlsjs engine).
As far as I understand core and Flash hls increment current time always, unless one *seeks* to a position _before_ the beginning of the dvr window. The advantage of the approach is certainly that the controls are less boring to watch ;-)

@nnarhinen - I have no idea what the general consensus/expecation is regarding a DVR UI.

Clearly some, including @popler, expect a "static" window (for non-incremental DVR), and it's the dash.js approach, see my demo above or http://vm2.dashif.org/livesim/testpic_2s/Manifest.mpd in their player at http://dashif.org/reference/players/javascript/v2.4.0/samples/dash-if-reference-player/

**Comment by blacktrash** [comment] 2017-01-21 16:35
@popler - indeed I could reproduce the progress bar problem, kinda the reverse of what I observed in native playback.

We first should decide _what_ approach should be implemented ;-)

**Comment by popler** [comment] 2017-01-21 16:53
@blacktrash - my opinion you know:) 
Do you have any ETA for 7.0.1?

**Comment by popler** [comment] 2017-01-21 17:37
@blacktrash - I can confirm that it does not try to go before of the dvr window, but ... when I rewind to start of the dvr window I can't go back to live because of progress bar error.

**Comment by blacktrash** [comment] 2017-01-21 18:31
@popler - fingers crossed I've finally groked the "dynamic" window, as in core; I had a "static" dvr window conceptual leftover in there. Please try again.

@nnarhinen - if we want to offer an optional "static" dvr window, it could probably be implemented with relative ease by subtracting seekable.start(null) from seekable.end(null) to obtain duration and `end` property of the dvrwindow event.

**Comment by blacktrash** [comment] 2017-01-21 19:23
@nnarhinen - I'm starting to like the "dynamic" window, but Flash hls behaves somewhat differently: if the start is out of bounds, seeking backwards resets the time counter so to speak, it basically starts at 0 again. Pretty clear when you have played longer than the window (a bit over 9m in our demo), and seek back to 0. Time should be 9m+, but it isn't. - http://demos.flowplayer.org/basics/dvr.html?hlsjs=false

**Comment by popler** [comment] 2017-01-21 22:37
@blacktrash - maybe I'm doing something wrong, but I can not see "static" window with my player on http://www.popler.tv/embed/player7.php?user=poplerhd or on yours website https://flowplayer.blacktrash.org/fp7/dvr.html. I mean the left time display is going on, but I can click on progress bar and video is rewind to start of the dvr window. Going back to live by clicking on progress bar is also working.

**Comment by blacktrash** [comment] 2017-01-21 23:42
@popler - I wanted to implement the "dynamic" one first, which is the proposal by core. Sorry for the misunderstanding, but thanks for confirming.
It doesn't work with Flash HLS yet, though.

**Comment by blacktrash** [comment] 2017-01-21 23:53
With the 7.0.0 implementation one can even click on "Live" and see the remaining time of the "static" DVR window. - Which is why I'm not sure whether using a click on "Live" to go  to the Live position - https://github.com/flowplayer/flowplayer/commit/0e824482002fb0c0c407e983d8414e144f293d02 - is a better idea or more informative, as in: http://demos.1111f.flowplayer.me/basics/dvr.html
After all one can do this by just scrubbing to the end of controls (provided the implementation works, as it does now for 7.0.0 with native hls and hlsjs) - @nnarhinen?

**Comment by popler** [comment] 2017-01-22 08:56
@blacktrash going back to live by clicking is much easier and intuitive than using scrubber. People are used to doing it this way by a some video portals.

**Comment by blacktrash** [comment] 2017-01-22 11:05
My proposal is to do both:
```
{current time} / { (toggle) duration or remaining (of dvr window) } "Live"
```
i.e. Make "Live" a _separate_ button serving as live indicator and jump to live position on click.
The lenght of this conversation is the perfect argument to do so. At least I would have found much quicker about:
- the advantages of the "dynamic" dvr window approach
- the fact that the "dynamic" approach worked only with native hls so far (now it works with native and hlsjs; todo: Flash HLS)

That way users would grasp it quicker as well.

It would look and work like VOD time display, only
- with the _additional_ Live indicator/jump widget
- the time indicator will be larger than the "duration" (of the DVR window) once the playlist is refreshed

This would also take care automatically of EVENT type incremental only playlists. - For those it can be investigated if and whether we can detect when the increments halts and the "Live" widget be removed.

**Comment by popler** [comment] 2017-01-22 12:22
@blacktrash - additional Live indicator is good idea, but option to hide right time indicator will be useful in such situation.

**Comment by blacktrash** [comment] 2017-01-22 19:27
Really easy to do with CSS in Flowplayer 7 (no extra adjustments needed):
```css
.flowplayer .fp-duration {
  display: none;
}
```

**Comment by nnarhinen** [comment] 2017-01-23 08:08
Remaining DVR window time is most likely something end users are not interested in. They can see from the timeline they are not in the end of the live position.

**Comment by nnarhinen** [comment] 2017-01-23 08:09
I will make them separate buttons if much asked for (by implementors)

**Comment by blacktrash** [comment] 2017-01-23 08:18
ok - arguably most users are, ermh, used to a "static" DVR window, e.g. https://support.jwplayer.com/customer/portal/articles/1430265-dvr-live-streaming - so I thought it would clarify our approach.

**Comment by nnarhinen** [comment] 2017-01-23 08:19
Please explain "static" vs "dynamic". In the jwplayer example you linked the scrubber jumps back a few pixels every now and then - is the DVR window then static or dynamic?

**Comment by popler** [comment] 2017-01-23 10:47
@nnarhinen this is static DVR window on @blacktrash example. The time on the left side is static as you can see, so DVR windows is limit to almost 10 minutes on server. There is one more useful option on this example - bubble with time above scrubber.

**Comment by blacktrash** [comment] 2017-01-23 10:50
"static" refers to _display_ (hence the quotes), and with dash you can actually get a completely static display: https://flowplayer.blacktrash.org/fp7/dash-live.html - with HLS this is not possibly in an entirely clean fashion because there's no actual standard for it, so the DVR window duration changes slightly at each playlist refresh; its duration oscillates inside an interval of one segment duration.
"static" display here is meant to say that the displayed current time does not increment - unless you seek forward inside the DVR window.

**Comment by blacktrash** [comment] 2017-01-23 10:57
What I call "dynamic" is when the time counter increments with "viewing time per session" so to speak. It increments _while_ viewing as opposed to static, where it never changes its value (or only within HLS segment duration), only when seeking to a different position inside the DVR window (the dash example above).

**Comment by popler** [comment] 2017-01-24 19:27
@blacktrash - I would like to make FP with DVR looking like livestream player (https://livestream.com/watch). I mean scrubber with rewind bubble, LIVE/DVR icon on the top and LIVE button. In your opinion, is it possible after 7.0.1 will be ready?

**Comment by nnarhinen** [comment] 2017-01-27 10:36
@blacktrash I need more debuggin information. 

 1. Open http://demos.1127f.flowplayer.me/basics/dvr.html?hlsjs=false
 2. Open javascript console
 3. `localStorage.flowplayerDebug = true;`
 4. refresh page
 5. Do your magic to make the player misbehave after seek
 6. Look for the "seek requested" log entries and paste here

![image](https://cloud.githubusercontent.com/assets/265438/22367989/06e30840-e48d-11e6-8cb4-df94e2dca1b1.png)

**Comment by blacktrash** [comment] 2017-01-27 11:30
Forgot to refresh page, but this already shows how the duration increases:
```
INFO:HLSNetStream:close
(unknown) INFO:HLSNetStream:seek(0)
(unknown) INFO:HLSNetStream:play(-1)
(unknown) INFO:HLSNetStream:seek(-1)
(unknown) INFO:HLSNetStream:pause
localStorage.flowplayerDebug = true;
true
VM285:1 INFO:HLSNetStream:resume
flowplayer(0).video.duration
641.2640000000005
flowplayer(0).video.duration
645.6680000000005
flowplayer(0).video.duration
1074.4860000000003
VM2002:1 INFO:HLSNetStream:seek(1040.338542416298)
VM2016:1 INFO:HLSNetStream:seek(911.0668558706399)
VM2026:1 INFO:HLSNetStream:seek(548.0185059937157)
VM2036:1 INFO:HLSNetStream:seek(1027.1421200744467)
```
Once the duration exceeds the one available on ready seeking doesn't work as expected. Just by doing nothing you can see how the live position (the rightmost point of the progress bar) moves to the left over time.

**Comment by blacktrash** [comment] 2017-01-27 11:39
just making sure I'm using not any cached swf ...

**Comment by blacktrash** [comment] 2017-01-27 12:52
Seems to work better, but seeking to 0 may still fail, sometimes works on 2nd attempt; the first and last seeks in the log excerpt went wrong:
```
-- debug: seek(680.411999999999) undefined
flowplayer.min.js:6 -- debug: seek requested (seconds, seekOffset, duration) - (680, 680, 596)
VM22961:1 INFO:HLSNetStream:seek(680.411999999999)
flowplayer.min.js:6 -- seek 680.411999999999
flowplayer.min.js:6 -- debug: seek(697.4809999999993) undefined
flowplayer.min.js:6 -- debug: seek requested (seconds, seekOffset, duration) - (697, 697, 596)
VM23020:1 INFO:HLSNetStream:seek(697.4809999999993)
flowplayer.min.js:6 -- seek 697.4809999999993
flowplayer.min.js:6 -- debug: seek(1281.864642198163) undefined
flowplayer.min.js:6 -- debug: seek requested (seconds, seekOffset, duration) - (1281, 697, 596)
VM23038:1 INFO:HLSNetStream:seek(1281.864642198163)
flowplayer.min.js:6 -- seek 1281.864642198163
flowplayer.min.js:6 -- debug: seek(1291.6706858852488) undefined
flowplayer.min.js:6 -- debug: seek requested (seconds, seekOffset, duration) - (1291, 702, 596)
VM23058:1 INFO:HLSNetStream:seek(1291.6706858852488)
flowplayer.min.js:6 -- seek 1291.6706858852488
flowplayer.min.js:6 -- debug: seek(710.732898837278) undefined
flowplayer.min.js:6 -- debug: seek requested (seconds, seekOffset, duration) - (710, 706, 596)
VM23079:1 INFO:HLSNetStream:seek(710.732898837278)
flowplayer.min.js:6 -- seek 710.732898837278
```

**Comment by blacktrash** [comment] 2017-01-27 12:53
But overall it looks improved. Display-wise the progress peak slowly wanders to the left, but functionality-wise it usually works at least at the 2nd attempt.

**Comment by blacktrash** [comment] 2017-01-27 12:58
Display-wise also the current time resets itself to the live-window duration after a final successful seek attempt. Here is some more logging:
```
INFO:HLSNetStream:seek(710.732898837278)
flowplayer.min.js:6 -- seek 710.732898837278
flowplayer.min.js:6 -- debug: seek(819.9999999999976) undefined
flowplayer.min.js:6 -- debug: seek requested (seconds, seekOffset, duration) - (819, 819, 596)
VM23501:1 INFO:HLSNetStream:seek(819.9999999999976)
flowplayer.min.js:6 -- seek 819.9999999999976
flowplayer.min.js:6 -- debug: seek(1413.8534721327205) undefined
flowplayer.min.js:6 -- debug: seek requested (seconds, seekOffset, duration) - (1413, 820, 596)
VM23515:1 INFO:HLSNetStream:seek(1413.8534721327205)
flowplayer.min.js:6 -- seek 1413.8534721327205
flowplayer.min.js:6 -- debug: seek(827.518593848183) undefined
flowplayer.min.js:6 -- debug: seek requested (seconds, seekOffset, duration) - (827, 824, 596)
VM23831:1 INFO:HLSNetStream:seek(827.518593848183)
flowplayer.min.js:6 -- seek 827.518593848183
flowplayer.min.js:6 -- debug: seek(910.2460513318227) undefined
flowplayer.min.js:6 -- debug: seek requested (seconds, seekOffset, duration) - (910, 905, 596)
VM23841:1 INFO:HLSNetStream:seek(910.2460513318227)
flowplayer.min.js:6 -- seek 910.2460513318227
flowplayer.min.js:6 -- debug: seek(4.44089883727912) undefined
flowplayer.min.js:6 -- debug: seek requested (seconds, seekOffset, duration) - (4, 0, 596)
VM23851:1 INFO:HLSNetStream:seek(4.44089883727912)
flowplayer.min.js:6 -- seek 4.44089883727912
flowplayer.min.js:6 -- debug: seek(602.8582521763504) undefined
flowplayer.min.js:6 -- debug: seek requested (seconds, seekOffset, duration) - (602, 15, 596)
VM23890:1 INFO:HLSNetStream:seek(602.8582521763504)
flowplayer.min.js:6 -- seek 602.8582521763504
flowplayer.min.js:6 -- debug: seek(4.0267463427325225) undefined
flowplayer.min.js:6 -- debug: seek requested (seconds, seekOffset, duration) - (4, 0, 596)
VM23904:1 INFO:HLSNetStream:seek(4.0267463427325225)
flowplayer.min.js:6 -- seek 4.0267463427325225
flowplayer.min.js:6 -- debug: seek(620.2426204246644) undefined
flowplayer.min.js:6 -- debug: seek requested (seconds, seekOffset, duration) - (620, 26, 596)
VM24003:1 INFO:HLSNetStream:seek(620.2426204246644)
flowplayer.min.js:6 -- seek 620.2426204246644
```

**Comment by blacktrash** [comment] 2017-01-27 13:02
This is a 2-attempt log, first jumps forward, 2nd succeeds:
```
-- debug: seek(155.25744135363988) undefined
flowplayer.min.js:6 -- debug: seek requested (seconds, seekOffset, duration) - (155, 153, 596)
VM25696:1 INFO:HLSNetStream:seek(155.25744135363988)
flowplayer.min.js:6 -- seek 155.25744135363988
flowplayer.min.js:6 -- debug: seek(16.74374634273248) undefined
flowplayer.min.js:6 -- debug: seek requested (seconds, seekOffset, duration) - (16, 13, 596)
VM25726:1 INFO:HLSNetStream:seek(16.74374634273248)
flowplayer.min.js:6 -- seek 16.74374634273248
```

**Comment by blacktrash** [comment] 2017-01-27 13:10
@nnarhinen - you can observe this yourself when the current time doesn't increment properly, it should never go to 0 after a seek to 0 becuase of the "dynamic/incremental" window implementaion, but it does.

**Comment by blacktrash** [comment] 2017-01-27 13:14
i.e., with our implementation the displayed seek offset should always increment over time, never go back to zero (with this stream which features a _sliding_ window, would be different with an incremental-only EVENT playlist). - Maybe that is not possible with Flash, but that is the behavior you implemented for native and I for hlsjs.

**Comment by blacktrash** [comment] 2017-01-27 13:35
This is what you see when you just let the stream run for a while at live position:
<img width="1194" alt="screen shot 2017-01-27 at 1 32 30 pm" src="https://cloud.githubusercontent.com/assets/168338/22372515/1ff1cbca-e495-11e6-8fc8-cb19dd4db93f.png">
The progress peak has moved to the left. This does not happen in native or with hlsjs, where the progress bar stays more or less full (minus required live-sync pre-buffering).

**Comment by blacktrash** [comment] 2017-01-27 13:37
The *displayed* DVR window is increasing, but of course the *actual* window is not.

**Comment by blacktrash** [comment] 2017-01-27 13:47
And when you seek in the above state, the current time display is reset, and:
- to beginning: fails at first attempt, works usually at 2n
- to Live: works - but current time is *de*cremented (reset)

**Comment by blacktrash** [comment] 2017-01-27 13:53
With native or hlsjs `flowplayer().video.buffer` stays at the same value, with Flash HLS it increments.

**Comment by blacktrash** [comment] 2017-01-27 14:05
According to @mangui there is no equivalent to hlsjs' [LEVEL_UPDATED](https://github.com/dailymotion/hls.js/blob/master/API.md#runtime-events) event, which I presume is fired when the current playlist is refreshed, and (potentially bufferd?) segments should be unreachable.
So it looks to me like with Flash HLS the `seekOffset` prop of the video object is not updated properly, same for the `start` prop given to the dvrwindow event.
Maybe with Flash HLS `seekOffset` and `start` should always be set to `video.buffer - {initially determined DVR window duration}` - unless there is a way to listen to the current level being updated.

**Comment by blacktrash** [comment] 2017-01-27 14:25
Sorry, I was wrong, with hlsjs the `video.buffer` also increases, but the `seekOffset` is updated correctly because of LEVEL_UPDATED.

**Comment by nnarhinen** [comment] 2017-01-27 14:39
Sorry for being stupid, but could you please give me the most simplified version of the problem description and how you would expect things to work. I don't understand half of what you have written so far.

Something in the sense of 

Steps to reproduce:
1. Start stream
2. Do X

What I would have expected to see:
1. Rainbows

What I actually saw:
1. Kittens

**Comment by nnarhinen** [comment] 2017-01-27 14:39
And if there are multiple problems, let's start with one problem at a time.

**Comment by blacktrash** [comment] 2017-01-27 15:39
1. Start stream
2. Wait .... at least until you see that the progress peak has move to the left (to make it obvious)
3. Seek to end or beginning
4. once successful (not all the time), click "Live"

Expect to see: current time is higher than than DVR window duration

What you see is this: time is at DVR duration - like here: http://d12zt1n3pd4xhr.cloudfront.net/fp/test/flashls-dvr-time-reset.mov

**Comment by blacktrash** [comment] 2017-01-27 15:59
ok, *totally* simple, but needs way more patience:
1. Start stream
2. wait wait wait

Expected: right end of progress bar stays near right edge of scrubber, "Live" stays highlighted

Actually: right end of progress bar moves towards the left, "Live" is (sometimes!) not highlighted anymore

**Comment by blacktrash** [comment] 2017-01-27 16:08
And once this is all sorted out, we have to think about how to handle very long pauses ... :-(
That's not really working display-wise in any engine, native engine is unusable, haven't gotten around to hlsjs yet. Very time consuming.

**Comment by blacktrash** [comment] 2017-01-27 17:17
Maybe this helps to spot it quicker: `flowplayer.common.css(document.querySelector(".fp-remaining"), "display", "block");` - with flash hls this increments during playback, otherwise it does not.

**Comment by blacktrash** [comment] 2017-01-28 15:37
@nnarhinen - there is now http://demos.dev94.flowplayer.us/bug/1102.html?hlsjs=false in the hope that it helps making the issue *visible*.

**Comment by nnarhinen** [comment] 2017-01-30 12:54
http://demos.1127f.flowplayer.me/bug/1102.html

**Comment by nnarhinen** [comment] 2017-01-30 12:55
I'm reading the values directly from the flashls objects. so either @mangui has to take a look or then we just try to fix the seek thing and keep the display inconsistence.

It seems the flashls version has always 15secs more duration.

**Comment by blacktrash** [comment] 2017-01-30 13:22
> It seems the flashls version has always 15secs more duration.

15 secs is 3 times TARGETDURATION of the current playlist (by default) in hlsjs - same as native playback in Safari. HLS can never be entirely live, there must be an advance buffer to ensure playback. See the liveSyncDurationCount https://github.com/dailymotion/hls.js/blob/master/API.md#livesyncdurationcount and liveSyncDuration https://github.com/dailymotion/hls.js/blob/master/API.md#livesyncduration options for hls.js

It's also what hlsjs subtracts from seekable(end) in the ready and progress events.

**Comment by nnarhinen** [comment] 2017-01-30 13:31
Where's the substraction done?

**Comment by nnarhinen** [comment] 2017-01-30 13:40
Did https://github.com/flowplayer/flowplayer/pull/1127/commits/b4a7096e5de378344bd715ac6191b544eaed5fdb help to the seeking problem?

**Comment by nnarhinen** [comment] 2017-01-30 13:49
* `hls_initiallivemanifestsize` (default 1) - Number of segments needed to start playback of Live stream.

I wonder if that setting in flashls is the samae as `liveSyncDurationCount` in hlsjs? And can it be used in same manner.

**Comment by blacktrash** [comment] 2017-01-30 14:16
My guess would be that is only for startup.
Do you have access to the current level?
The subtraction is not that important imho, at least hlsjs works ok as well with that stream at least when I omit it, the only effect is that seeking to end makes the player buffer for a moment.
The problem with flashls is that an ever larger part on the left of the scrubber becomes unusable over time. One is also easily side-tracked by the scrubber display which shows an increasing buffer portion on the right (wrong because live position is always more or less rightmost), whereas in fact there is an increasing unavailable buffer on the left.
As duration - seekOffset stays the same, it looks like the player has enough info, but like it's not propagated to the UI?

**Comment by nnarhinen** [comment] 2017-01-31 07:15
> Did b4a7096 help to the seeking problem? Testable at the url above.

@blacktrash ping

**Closed** 2017-01-31 09:44 UTC

**Comment by popler** [comment] 2017-01-31 17:46
@blacktrash I still have a problem with static DVR window. Please check http://www.popler.tv/embed/player7.php?user=poplerhd. There is 10 min static DVR window on the server.
Time on the left getting greater value than this window. I'm using FP 7.0.1 with flowplayer.hls.min.js 1.0.4 plugin. Is there any additional option to make it work?

**Comment by popler** [comment] 2017-01-31 18:39
@blacktrash Please check the scrubber also. As you can see there is a big gap on the left. Probably only blue part should be clickable.

**Comment by blacktrash** [comment] 2017-02-01 10:39
@popler - let's take this to https://github.com/flowplayer/flowplayer/issues/1132

**Comment by popler** [comment] 2017-02-01 13:11
@blacktrash I reset a transcoder and server. Stream is played without errors, but gap on scrubber is still there. Maybe it depends on chunk duration? I'm using 10s, you are using 5-6s in your demo http://demos.1127f.flowplayer.me/bug/1102.html

**Comment by popler** [comment] 2017-02-01 13:16
@blacktrash I'm not sure, but as I understand the static DVR window (not increasing time on the left) is not implemented yet?

**Comment by blacktrash** [comment] 2017-02-01 13:23
No it isn't. And at the moment I don't see the need, even the implementation at https://livestream.com/watch you referenced increments time.

**Comment by popler** [comment] 2017-02-01 13:27
It is true. Point to you, but... :) They have nice timestamp indicator over the scrubber with time to rewind. It is something I'm trying to do -I wrote on FP forum.

**Comment by blacktrash** [comment] 2017-02-01 16:10
What I posted in the forum works with with native hls, and with flash hls (because the current time is reset on every seek with that engine anyway). With hlsjs it's more complex.
