### ISSUE TITLE
Embed video when title has non Latin characters

### ISSUE THREAD

**Issue by zivni** [flowplayer/flowplayer#1205] opened 2017-06-13 10:14 UTC
I set the title attribute of the clip object to some Hebrew text, Then when clicking the embed button, I get the following error in the console: 
```
Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at Object.e.shareUrl (http://releases.flowplayer.org/7.0.4/flowplayer.min.js:7:17697)
    at Object.e.embedCode (http://releases.flowplayer.org/7.0.4/flowplayer.min.js:6:31567)
    at HTMLAnchorElement.<anonymous> (http://releases.flowplayer.org/7.0.4/flowplayer.min.js:6:31995)
    at HTMLDivElement.r (http://releases.flowplayer.org/7.0.4/flowplayer.min.js:9:2838)
    at r (http://releases.flowplayer.org/7.0.4/flowplayer.min.js:8:31726)
    at HTMLDivElement.a (http://releases.flowplayer.org/7.0.4/flowplayer.min.js:8:31989)
    at HTMLDivElement.D (http://releases.flowplayer.org/7.0.4/flowplayer.min.js:9:1972)
```

**Comment by blacktrash** [comment] 2017-06-14 00:31
Seems to be a known problem with atob/btoa: https://developer.mozilla.org/en/docs/Web/API/WindowBase64/Base64_encoding_and_decoding#The_.22Unicode_Problem.22

**Comment by nnarhinen** [comment] 2017-11-03 08:58
Duplicate of #1239

**Closed by nnarhinen** 2017-11-03 08:58 UTC
