### ISSUE TITLE
iPhone playback crashes when you exit twice

### ISSUE THREAD

**Issue by foliovision** [flowplayer/flowplayer#831] opened 2015-06-03 14:29 UTC
Just stumbled upon a playback glitch on iPhone 6.1.1 and 7.0.3 (I used X code simulator for this one):

1) Open flowplayer.org/player
2) Play the video, the internal video player takes over the playback
3) Exit the playback after couple of seconds
4) Click to resume the video
5) Exit the playback again
6) Click to resume the video again - it won't ever load. Instead the error event gets triggered

Thanks!
Martin

**Comment by nnarhinen** [comment] 2015-06-04 05:54
I cannot reproduce this with the 8.3 iPhone simulator.

**Comment by anssip** [comment] 2015-06-04 06:02
I cannot reproduce on my iPhone 5s. @foliovision, how do you exit the playback? Using the "Done" button?

**Comment by nnarhinen** [comment] 2015-06-08 17:31
Closing this issue as it cannot be reproduced on our current devices and simulators.

**Comment by foliovision** [comment] 2015-06-12 12:16
@anssip yes, I use the "Done" button of the iPhone internal video player. What iOS is in your iPhone 52?

@nnarhinen does iPhone 8.3 support inline playback or not?

I'm still getting this behavior on: http://flowplayer.org/player

* iPhone with iOS 7.0.3 (Xcode simulator)
* iPod with iOS 6.1.6

**Comment by nnarhinen** [comment] 2015-06-12 16:50
@foliovision no, it uses the fullscreen player

**Comment by foliovision** [comment] 2015-06-17 09:01
I still suspect that while this works for you on iOS 8, there might be a problem in iOS 7 and 6. Could you please check these iOS version at least in Xcode?

**Comment by blacktrash** [comment] 2015-06-17 09:40
I can confirm problems, but no crashing, with simulated iOS 7.1: for me the "player" is stuck in loading state after the second exit (quick test).

**Comment by blacktrash** [comment] 2015-06-17 09:48
It basically does not unload cleanly.

**Comment by blacktrash** [comment] 2015-06-17 09:52
I can also repro the stuck in loading state with iOS 8 after exit, albeit more rarely.

**Comment by blacktrash** [comment] 2015-06-17 10:01
After starting and exiting a few times (also with different videos) I end up with this for iOS 8.3 - with 7.1 immediately after the 2nd exit:
![screen shot 2015-06-17 at 10 59 24 am](https://cloud.githubusercontent.com/assets/168338/8204368/fb7fdeb6-14df-11e5-9242-4d7b886f5ca9.png)

**Comment by nnarhinen** [comment] 2015-06-17 17:30
Fixed here, please conrifm: http://demos.862f.flowplayer.me/

**Comment by blacktrash** [comment] 2015-06-17 18:21
Confirming fix in iOS 7.1, 8.2, 8.3 simulators :+1:

**Closed** 2015-06-19 06:05 UTC
